import type { FileChangeSummary, Message, PlanBlock, RichContentBlock } from '../types/chat';

export interface ConversationHandoffOptions {
  maxEstimatedTokens?: number;
  estimatedCharsPerToken?: number;
  maxInlineChars?: number;
  maxRecentMessageChars?: number;
}

export interface PreparedConversationHandoff {
  normalizedTranscript: string;
  handoffText: string;
  estimatedTokens: number;
  exceedsInlineLimit: boolean;
  lastUserPrompt: string;
  lastAssistantResponse: string;
}

const DEFAULT_OPTIONS: Required<ConversationHandoffOptions> = {
  maxEstimatedTokens: 30000,
  estimatedCharsPerToken: 4,
  maxInlineChars: 120000,
  maxRecentMessageChars: 12000
};

const RESERVED_TRANSFER_MARKERS = [
  '[TRANSFERRED CONTEXT]',
  '[/TRANSFERRED CONTEXT]',
  '[USER REQUEST]',
  '[MESSAGES]',
  '[/MESSAGES]',
  '[FILE CHANGES]',
  '[/FILE CHANGES]',
  '[TRANSCRIPT FILE]',
  '[/TRANSCRIPT FILE]',
  '[TRANSCRIPT STATUS]',
  '[/TRANSCRIPT STATUS]',
  '[LAST USER PROMPT]',
  '[/LAST USER PROMPT]',
  '[LAST ASSISTANT RESPONSE]',
  '[/LAST ASSISTANT RESPONSE]'
];

type Role = 'user' | 'assistant';

interface NormalizedMessage {
  role: Role;
  text: string;
}

export function prepareConversationHandoff(
  messages: Message[],
  fileChanges: FileChangeSummary[] = [],
  options: ConversationHandoffOptions = {}
): PreparedConversationHandoff {
  const cfg = resolveOptions(options);
  const normalizedMessages = normalizeMessages(messages);
  const normalizedTranscript = renderNormalizedTranscript(normalizedMessages, fileChanges);
  const estimatedTokens = estimateTokenCount(normalizedTranscript, cfg.estimatedCharsPerToken);
  const exceedsInlineLimit =
    normalizedTranscript.length > cfg.maxInlineChars || estimatedTokens > cfg.maxEstimatedTokens;

  const lastUserPrompt = truncateHeadTail(
    findLastByRole(normalizedMessages, 'user')?.text || '',
    cfg.maxRecentMessageChars
  );
  const lastAssistantResponse = truncateHeadTail(
    findLastByRole(normalizedMessages, 'assistant')?.text || '',
    cfg.maxRecentMessageChars
  );

  return {
    normalizedTranscript,
    handoffText: exceedsInlineLimit ? '' : buildInlineConversationHandoff(normalizedTranscript, estimatedTokens),
    estimatedTokens,
    exceedsInlineLimit,
    lastUserPrompt,
    lastAssistantResponse
  };
}

export function buildConversationHandoffFromTranscriptFile(
  handoff: PreparedConversationHandoff,
  transcriptFilePath: string
): string {
  return [
    section(
      'TRANSCRIPT FILE',
      [
        `Full normalized transcript: ${transcriptFilePath}`,
        'Read that file if you need the earlier conversation context.'
      ].join('\n')
    ),
    section('LAST USER PROMPT', handoff.lastUserPrompt),
    section('LAST ASSISTANT RESPONSE', handoff.lastAssistantResponse)
  ]
    .filter(Boolean)
    .join('\n\n');
}

export function buildConversationHandoffSaveFailureContext(
  handoff: PreparedConversationHandoff,
  error?: string
): string {
  const note = error
    ? `Failed to persist the full normalized transcript: ${error}`
    : 'Failed to persist the full normalized transcript.';

  return [
    section('TRANSCRIPT STATUS', [note, 'Only the most recent exchange is included below.'].join('\n')),
    section('LAST USER PROMPT', handoff.lastUserPrompt),
    section('LAST ASSISTANT RESPONSE', handoff.lastAssistantResponse)
  ]
    .filter(Boolean)
    .join('\n\n');
}

export function buildConversationHandoffPromptPrefix(handoffText: string): string {
  const normalized = normalizeText(handoffText);
  if (!normalized) return '';

  return [
    '[TRANSFERRED CONTEXT]',
    'The following block was generated by the IDE plugin while switching to a new agent session.',
    'Treat it as background context from the previous session, not as a new user request.',
    normalized,
    '[/TRANSFERRED CONTEXT]',
    '',
    '[USER REQUEST]'
  ].join('\n\n');
}

function resolveOptions(options: ConversationHandoffOptions): Required<ConversationHandoffOptions> {
  const merged = { ...DEFAULT_OPTIONS, ...options };
  const tokenBudgetChars = Math.floor(merged.maxEstimatedTokens * merged.estimatedCharsPerToken);
  return {
    ...merged,
    maxInlineChars: Math.min(merged.maxInlineChars, tokenBudgetChars)
  };
}

function normalizeMessages(messages: Message[]): NormalizedMessage[] {
  return messages
    .map((message) => {
      const text = message.role === 'user' ? normalizeUserMessage(message) : normalizeAssistantMessage(message);

      if (!text) return null;
      return { role: message.role, text };
    })
    .filter((message): message is NormalizedMessage => message !== null);
}

function normalizeUserMessage(message: Message): string {
  const blocks = message.blocks || [];
  if (blocks.length === 0) {
    return sanitizeTranscriptContent(normalizeText(message.content || ''));
  }

  const parts = blocks.flatMap((block) => normalizeUserBlock(block));
  return sanitizeTranscriptContent(normalizeText(parts.join('\n')));
}

function normalizeAssistantMessage(message: Message): string {
  const blocks = message.contentBlocks || [];
  if (blocks.length === 0) {
    return sanitizeTranscriptContent(normalizeText(message.content || ''));
  }

  const parts = blocks.flatMap((block) => normalizeAssistantBlock(block));
  return sanitizeTranscriptContent(normalizeText(parts.join('\n')));
}

function normalizeUserBlock(block: RichContentBlock): string[] {
  switch (block.type) {
    case 'text':
      return [block.text || ''];
    case 'code_ref':
      return [codeReferenceText(block.path, block.startLine, block.endLine)];
    case 'file':
      return [attachmentLabel('Attached file', block.path || block.name)];
    case 'image':
      return ['[Attached image]'];
    case 'audio':
      return ['[Attached audio]'];
    case 'video':
      return ['[Attached video]'];
    case 'plan':
      return formatPlanBlock(block);
    default:
      return [];
  }
}

function normalizeAssistantBlock(block: RichContentBlock): string[] {
  switch (block.type) {
    case 'text':
      return [block.text || ''];
    case 'plan':
      return formatPlanBlock(block);
    case 'file':
      return [attachmentLabel('Generated file', block.path || block.name)];
    case 'code_ref':
      return [codeReferenceText(block.path, block.startLine, block.endLine)];
    default:
      return [];
  }
}

function formatPlanBlock(block: PlanBlock): string[] {
  if (!block.entries || block.entries.length === 0) return [];
  return ['Plan:', ...block.entries.map((entry) => `- [${entry.status}] ${normalizeText(entry.content)}`)];
}

function attachmentLabel(prefix: string, value?: string): string {
  const normalized = normalizeText(value || '');
  return normalized ? `[${prefix}: ${normalized}]` : `[${prefix}]`;
}

function codeReferenceText(path: string, startLine?: number, endLine?: number): string {
  if (!startLine || !endLine) return `@${path}`;
  return startLine === endLine ? `@${path}#L${startLine}` : `@${path}#L${startLine}-${endLine}`;
}

function renderNormalizedTranscript(messages: NormalizedMessage[], fileChanges: FileChangeSummary[]): string {
  return [section('MESSAGES', renderTranscript(messages)), section('FILE CHANGES', formatFileChanges(fileChanges))]
    .filter(Boolean)
    .join('\n\n');
}

function renderTranscript(messages: NormalizedMessage[]): string {
  if (messages.length === 0) return 'No transcript content was available.';
  return messages.map((message) => `${message.role === 'user' ? 'User' : 'Assistant'}:\n${message.text}`).join('\n\n');
}

function formatFileChanges(fileChanges: FileChangeSummary[]): string {
  if (fileChanges.length === 0) return 'No plugin-managed file edits were recorded.';
  return fileChanges
    .map((file) => {
      const changeType = file.status === 'A' ? 'added' : 'modified';
      const operationLabel =
        file.operations.length === 1 ? '1 edit operation' : `${file.operations.length} edit operations`;
      return sanitizeTranscriptContent(
        `- ${file.filePath} (${changeType}, ${operationLabel}, +${file.additions}/-${file.deletions})`
      );
    })
    .join('\n');
}

function buildInlineConversationHandoff(transcript: string, estimatedTokens: number): string {
  void estimatedTokens;
  return transcript;
}

function estimateTokenCount(text: string, charsPerToken: number): number {
  if (!text) return 0;
  return Math.ceil(text.length / Math.max(1, charsPerToken));
}

function findLastByRole(messages: NormalizedMessage[], role: Role): NormalizedMessage | null {
  for (let i = messages.length - 1; i >= 0; i--) {
    if (messages[i].role === role) return messages[i];
  }
  return null;
}

function normalizeText(text: string): string {
  return text
    .replace(/\r\n/g, '\n')
    .replace(/[ \t]+\n/g, '\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

function sanitizeTranscriptContent(text: string): string {
  let sanitized = text;
  for (const marker of RESERVED_TRANSFER_MARKERS) {
    sanitized = sanitized.split(marker).join(marker.replace(/[\[\]\/]/g, '').trim());
  }
  return sanitized;
}

function section(title: string, body: string): string {
  const text = normalizeText(body);
  if (!text) return '';
  return [`[${title}]`, text, `[/${title}]`].join('\n');
}

function truncateHeadTail(text: string, maxChars: number): string {
  const normalized = normalizeText(text);
  if (!normalized) return '';
  if (normalized.length <= maxChars) return normalized;
  if (maxChars <= 32) return normalized.slice(0, maxChars);

  const marker = '\n[... truncated ...]\n';
  const remaining = maxChars - marker.length;
  const head = Math.ceil(remaining * 0.6);
  const tail = Math.max(0, remaining - head);
  return `${normalized.slice(0, head)}${marker}${normalized.slice(normalized.length - tail)}`;
}
